import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'PMI-ACP',
      link: { type: 'doc', id: 'pmi-acp/start-here' },
      items: [
        {
          type: 'category',
          label: 'Module 01 – Agile Mindset',
          // Trang index của category (tự sinh), bạn có thể thêm description nếu muốn
          link: { type: 'generated-index', title: 'Module 01 – Agile Mindset' },
          // TỰ ĐỘNG lấy mọi file trong thư mục này theo sidebar_position
          items: [{ type: 'autogenerated', dirName: 'pmi-acp/module-01' }],
        },
        {
          type: 'category',
          label: 'Kế hoạch học',
          link: { type: 'generated-index', title: 'Kế hoạch học' },
          items: [
            'pmi-acp/plan/week-1',
            'pmi-acp/plan/week-2',
            'pmi-acp/plan/week-3',
            'pmi-acp/plan/week-4',
            'pmi-acp/plan/week-5',
            'pmi-acp/plan/week-6',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
