// pmi-acp-site/sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'PMI-ACP',
      link: { type: 'generated-index', title: 'PMI-ACP' },
      items: [
        { type: 'link', label: 'Start Here', href: '/start-here' },
        { type: 'doc', id: 'pmi-acp/course-outline', label: 'Course Outline' },

        {
          type: 'category',
          label: 'Kế hoạch học',
          link: {
            type: 'generated-index',
            title: 'Kế hoạch học',
            description: 'Lộ trình 6 tuần: mục tiêu, nội dung và các bài cần hoàn thành.',
          },
          items: [
            'pmi-acp/plan/week-1',
            'pmi-acp/plan/week-2',
            'pmi-acp/plan/week-3',
            'pmi-acp/plan/week-4',
            'pmi-acp/plan/week-5',
            'pmi-acp/plan/week-6',
          ],
        },

        {
          type: 'category',
          label: 'ACP Blueprint 2025',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'pmi-acp/blueprint-2025',
          },
          items: [
            {
              type: 'category',
              label: 'Domains (Tổng quan)',
              link: {
                type: 'generated-index',
                title: 'Domains (VI/EN)',
                description: 'Tổng quan 4 domain: Mindset, Leadership, Product, Delivery.',
              },
              items: [
                'pmi-acp/domains/domain-mindset',
                'pmi-acp/domains/domain-leadership',
                'pmi-acp/domains/domain-product',
                'pmi-acp/domains/domain-delivery',
              ],
            },

            // ===== Domains with explicit slugs =====
            {
              type: 'category',
              label: 'Mindset',
              collapsed: true,
              link: {
                type: 'generated-index',
                title: 'Mindset Domain',
                slug: '/pmi-acp/domains/mindset', // 👈 explicit slug
                description: 'Tổng quan domain Mindset.',
              },
              items: [{ type: 'autogenerated', dirName: 'pmi-acp/domains/mindset' }],
            },
            {
              type: 'category',
              label: 'Leadership',
              collapsed: true,
              link: {
                type: 'generated-index',
                title: 'Leadership Domain',
                slug: '/pmi-acp/domains/leadership', // 👈 explicit slug
                description: 'Tổng quan domain Leadership.',
              },
              items: [{ type: 'autogenerated', dirName: 'pmi-acp/domains/leadership' }],
            },
            {
              type: 'category',
              label: 'Product',
              collapsed: true,
              link: {
                type: 'generated-index',
                title: 'Product Domain',
                slug: '/pmi-acp/domains/product', // 👈 explicit slug
                description: 'Tổng quan domain Product.',
              },
              items: [{ type: 'autogenerated', dirName: 'pmi-acp/domains/product' }],
            },
            {
              type: 'category',
              label: 'Delivery',
              collapsed: true,
              link: {
                type: 'generated-index',
                title: 'Delivery Domain',
                slug: '/pmi-acp/domains/delivery', // 👈 explicit slug
                description: 'Tổng quan domain Delivery.',
              },
              items: [{ type: 'autogenerated', dirName: 'pmi-acp/domains/delivery' }],
            },
          ],
        },

        {
          type: 'category',
          label: 'ECO (Exam Content Outline)',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'ECO Cheatsheets',
            description: 'Ghi chú nhanh & checklist bám theo ECO 2025 để ôn tập trọng tâm.',
          },
          items: [{ type: 'autogenerated', dirName: 'pmi-acp/eco' }],
        },

        {
          type: 'category',
          label: 'Mock & Exam Prep',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Mock & Exam Prep',
            description: 'Mini mock, domain drills, mock 50/120, review playbook, lưu ý ngày thi.',
          },
          items: [{ type: 'autogenerated', dirName: 'pmi-acp/mock' }],
        },
      ],
    },
  ],
};

export default sidebars;
