import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Trang mở đầu khu PMI-ACP
    { type: 'doc', id: 'pmi-acp/start-here' },

    // Module 01: tự động lấy tất cả file trong docs/pmi-acp/module-01/
    {
      type: 'category',
      label: 'Module 01 – Agile Mindset',
      // Khi click vào label, mở Lesson 01 (id hiện có)
      link: { type: 'doc', id: 'pmi-acp/module-01/m01-lesson-01' },
      items: [{ type: 'autogenerated', dirName: 'pmi-acp/module-01' }],
    },

    // Study plan giữ nguyên các tuần
    {
      type: 'category',
      label: 'Kế hoạch học',
      link: { type: 'generated-index', title: 'Kế hoạch học' },
      items: [
        'pmi-acp/plan/week-1',
        'pmi-acp/plan/week-2',
        'pmi-acp/plan/week-3',
        'pmi-acp/plan/week-4',
        'pmi-acp/plan/week-5',
        'pmi-acp/plan/week-6',
      ],
    },
  ],
};

export default sidebars;
